# Generated by Django 4.1.1 on 2022-10-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_detail_product_order_detail_order_detail_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderproducts',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='app.Detail', to='app.product'),
        ),
    ]
